# Refrax — item.properties

item.10001 = torch
item.10002 = lantern
item.10003 = soul_torch soul_lantern
item.10004 = glowstone jack_o_lantern shroomlight
item.10005 = sea_lantern
item.10006 = redstone_lamp
item.10007 = magma_block campfire
item.10008 = lava_bucket
item.10009 = end_rod
item.10010 = beacon
item.10011 = ochre_froglight
item.10012 = verdant_froglight
item.10013 = pearlescent_froglight
item.10014 = amethyst_cluster large_amethyst_bud medium_amethyst_bud small_amethyst_bud
item.10015 = sculk_sensor calibrated_sculk_sensor sculk_catalyst
item.10016 = crying_obsidian respawn_anchor
item.10017 = glow_lichen glow_berries
item.10018 = nether_portal
item.10020 = redstone_torch
item.10021 = enchanting_table
item.10022 = candle white_candle orange_candle magenta_candle light_blue_candle yellow_candle lime_candle pink_candle gray_candle light_gray_candle cyan_candle purple_candle blue_candle brown_candle green_candle red_candle black_candle
item.10023 = copper_bulb exposed_copper_bulb weathered_copper_bulb oxidized_copper_bulb waxed_copper_bulb waxed_exposed_copper_bulb waxed_weathered_copper_bulb waxed_oxidized_copper_bulb
item.10024 = copper_torch exposed_copper_torch weathered_copper_torch oxidized_copper_torch copper_lantern exposed_copper_lantern weathered_copper_lantern oxidized_copper_lantern waxed_copper_lantern waxed_exposed_copper_lantern waxed_weathered_copper_lantern waxed_oxidized_copper_lantern
